# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46f1d988aca79526f3d05ffe80e40daa9d0a4bb78b2fa92450fe42663277f773b904738119739e4e51a97b91d9c5cd38e038c962395fe2efb2598f73d2c95842

test:
  secret_key_base: 12077d5bd61e490e1f4ca5f686f05bd34954d5d2d45472751ef5df638b9cd90a9b3152a2a9921fa58e51cc79941e1e58c37a3ded1e2b7a77e0464ff0f284f46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
